title: DroidYangon
url: "https://droidyangon.org"
author : DroidYangon
description: |
  DroidYangon will take place in Yangon, Myanmar
  in July 9th, 2019!
enforce_ssl: "https://droidyangon.org"
relative_permalinks: false
permalink: news/:title/  # permalink: date
timezone: Asia/Yangon

include:
  - _pages

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .editorconfig
  - .gitignore
  - .surgeignore
  - bower_components
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - deploy_surge.sh
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - NOTES.md
  - package*.json
  - Procfile
  - Rakefile
  - README.md
  - vendor

# We need `future` to allow our schedule to work :/
future: true

collections:  # process the _data folder
  components:
    output: false
  schedule:
    output: true
    permalink: /:collection/:name/
  organizers:
    output: false
    permalink: /:collection/
  sponsors:
    output: false
    permalink: /:collection/
  places:
    output: false
    permalink: /:collection/

# SEO Plugin settings

twitter:
  username: droidyangon

# This is the default logo that people see with opengraph
# logo: /static/2018-logos/squares-and-social/djangocon-square.png
logo: /static/img/social/avatar-main.png


# Frontmatter fallback settings
# This is the default logo that people see on blog posts
defaults:
  - scope:
      path: ""
    values:
      image: /static/img/social/avatar-main.png

# Our DjangoCon US settings...
contact_us_email: "hello@droidyangon.org"
sponsors_email: "partners@droidyangon.org"

# Our DjangoCon US links
sponsorship_prospectus: "https://drive.google.com/file/d/1gPE-iGJVJjglf-1o5wVV_qnfVgVt6Gb-/view"
financial_aid_application: "https://docs.google.com/forms/d/e/1FAIpQLSfqOQJNXDSftszH5Ar_LQT6Y0IcvuRUaXTC9ERS6h6PTKsvHg/viewform"
cfp_application: "https://www.papercall.io/djangocon-us-2018"
hotel_reservation_link: "http://www.marriott.com/meeting-event-hotels/group-corporate-travel/groupCorp.mi?resLinkData=DjangoCon%20US%202018%5Esanmv%60djcdjca%60169.00%60USD%60false%604%6010/13/18%6010/20/18%609/13/18&app=resvlink&stop_mobi=yes"
ticket_link: "https://ti.to/defna/djangocon-us-2018"
slack_link: ""

github: [metadata]
facebook:
  app_id: 280981518972848
